name: Build Sing-Box iOS Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Xcode environment
        # 确保使用 macOS 自带 Xcode
        run: xcode-select -p


      - name: Build Release Unsigned
        # working-directory: SFI
        run: |
          xcodebuild -list -project sing-box.xcodeproj
          xcodebuild \
            -project sing-box.xcodeproj \
            -scheme sing-box \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      - name: Package IPA
        # working-directory: SFI
        run: |
          cd build/Build/Products/Release-iphoneos
          mkdir -p Payload
          cp -r sing-box.app Payload/
          zip -r ../sing-box-unsigned.ipa Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-ios-unsigned-ipa
          path: build/Build/Products/Release-iphoneos/sing-box-unsigned.ipa
